# Generated by Django 4.2.4 on 2023-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_rename_street_airport_airport_name_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
