# Generated by Django 4.2.4 on 2023-08-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_rename_name_passenger_first_name_passenger_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='street',
            new_name='airport_name',
        ),
    ]
