# Generated by Django 4.2.4 on 2023-08-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_rename_street_airport_airport_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='first_name',
        ),
    ]
