# Generated by Django 4.2.4 on 2023-08-22 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('img', models.URLField(max_length=1000)),
                ('video', models.URLField(max_length=1000)),
                ('followers', models.ManyToManyField(related_name='followers', to='network.follower')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_likes', to='network.post')),
                ('user_like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_likes', to='network.post')),
            ],
        ),
    ]
