# Generated by Django 4.2.4 on 2023-08-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='multimedia_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
