# Generated by Django 4.2.4 on 2023-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_img_post_multimedia_link_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
