# Generated by Django 4.2.4 on 2023-08-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_follow_remove_user_followers_delete_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_like',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_like', to='network.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
