# Generated by Django 4.2.4 on 2023-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
            ],
        ),
    ]
