# Generated by Django 4.2.4 on 2023-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_flight_delete_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airport',
        ),
    ]
