# Generated by Django 4.2.4 on 2023-08-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_flight_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airport_flights', to='flights.airport'),
            preserve_default=False,
        ),
    ]
