# Generated by Django 4.2.4 on 2023-08-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airport',
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_destination', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_origin', to='flights.airport'),
        ),
    ]
