# Generated by Django 4.2.4 on 2023-08-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_flight_destination_alter_flight_origin_and_more'),
    ]

    operations = [
    ]
