# Generated by Django 4.2.4 on 2023-08-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_comment_bid_auctionlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='users',
            new_name='user',
        ),
    ]
