# Generated by Django 4.2.4 on 2023-08-11 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_closing_on_auctionwinner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionWins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='auction_winner',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='closing_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 17, 7, 810351)),
        ),
        migrations.DeleteModel(
            name='AuctionWinner',
        ),
        migrations.AddField(
            model_name='auctionwins',
            name='auction',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='auctionwins',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='auctionwins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
