# Generated by Django 4.2.4 on 2023-08-11 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionwins_remove_auctionlisting_auction_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionwins',
            name='bid',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='closing_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 56, 58, 439893)),
        ),
    ]
