# Generated by Django 4.2.4 on 2023-08-12 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionlisting_closing_on_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='closing_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 17, 15, 1, 596655)),
        ),
    ]
